In [1]:
import numpy as np

# 예시: 0과 1로 구성된 5개의 컬럼을 가진 10개의 데이터
data = np.array([
    [0, 1, 0, 1, 0],
    [1, 0, 1, 1, 0],
    [0, 1, 1, 0, 0],
    [1, 1, 0, 1, 1],
    [0, 0, 1, 0, 1],
    [1, 1, 1, 1, 0],
    [0, 1, 0, 0, 1],
    [1, 1, 1, 1, 1],
    [0, 0, 0, 1, 0],
    [1, 0, 1, 0, 1]
])

# 데이터 출력
print("데이터:\n", data)


데이터:
 [[0 1 0 1 0]
 [1 0 1 1 0]
 [0 1 1 0 0]
 [1 1 0 1 1]
 [0 0 1 0 1]
 [1 1 1 1 0]
 [0 1 0 0 1]
 [1 1 1 1 1]
 [0 0 0 1 0]
 [1 0 1 0 1]]


In [2]:
# 예: 첫 번째 컬럼 (0번 인덱스)와 두 번째 컬럼 (1번 인덱스) 값이 모두 1인지 확인
column1 = data[:, 0]  # 첫 번째 컬럼
column2 = data[:, 1]  # 두 번째 컬럼

# 두 컬럼 값이 모두 1인 행을 찾음
rows_with_both_ones = np.where((column1 == 1) & (column2 == 1))

# 결과 출력
print("두 컬럼 값이 모두 1인 행의 인덱스:", rows_with_both_ones[0])


두 컬럼 값이 모두 1인 행의 인덱스: [3 5 7]


In [3]:
import numpy as np

# 예시 데이터 (5개의 컬럼을 가진 10개의 행)
data = np.array([
    [0, 1, 0, 1, 0],
    [1, 0, 1, 1, 0],
    [0, 1, 1, 0, 0],
    [1, 1, 0, 1, 1],
    [0, 0, 1, 0, 1],
    [1, 1, 1, 1, 0],
    [0, 1, 0, 0, 1],
    [1, 1, 1, 1, 1],
    [0, 0, 0, 1, 0],
    [1, 0, 1, 0, 1]
])

# 선택할 n개의 컬럼 (여기서는 0번, 1번, 3번 컬럼을 예로 듬)
n_columns = [0, 1, 3]

# n개의 컬럼 값이 모두 1인 행을 찾음
rows_with_all_ones = np.where(np.all(data[:, n_columns] == 1, axis=1))

# 결과 출력
print("n개의 컬럼 값이 모두 1인 행의 인덱스:", rows_with_all_ones[0])


n개의 컬럼 값이 모두 1인 행의 인덱스: [3 5 7]


In [37]:
import numpy as np

# 예시 데이터 (5개의 컬럼을 가진 10개의 행)
data = np.array([
    [0, 1, 0, 1, 0],
    [1, 0, 1, 1, 0],
    [0, 1, 1, 0, 0],
    [1, 1, 0, 1, 1],
    [0, 0, 1, 0, 1],
    [1, 1, 1, 1, 0],
    [0, 1, 0, 0, 1],
    [1, 1, 1, 1, 1],
    [0, 0, 0, 1, 0],
    [1, 0, 1, 0, 1]
])

# 선택할 n개의 컬럼 (여기서는 0번, 1번, 3번 컬럼을 예로 듬)
n_columns = [0, 1, 3]

# n개의 컬럼 값이 모두 1인 행을 찾음
#rows_with_all_ones = np.where(np.all(data[:, n_columns] == 1, axis=1))
rows_with_all_ones = np.where(np.all(data == 1, axis=1))

# 결과 출력
print("n개의 컬럼 값이 모두 1인 행의 인덱스:", rows_with_all_ones[0])


n개의 컬럼 값이 모두 1인 행의 인덱스: [7]


In [5]:
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity

# 예시 DataFrame
data = {
    'A': [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
    'B': [1, 0, 1, 1, 0, 1, 1, 1, 0, 0],
    'C': [1, 0, 0, 0, 0, 1, 1, 1, 0, 0]
}
df = pd.DataFrame(data)


In [6]:
# C 배열을 Numpy 배열로 변환
c_array = df['C'].values.reshape(1, -1)

# A와 B 배열을 Numpy 배열로 변환
a_array = df['A'].values.reshape(1, -1)
b_array = df['B'].values.reshape(1, -1)

# 코사인 유사도 계산
similarity_a = cosine_similarity(c_array, a_array)[0][0]
similarity_b = cosine_similarity(c_array, b_array)[0][0]

# 결과 출력
print(f"C와 A의 코사인 유사도: {similarity_a:.4f}")
print(f"C와 B의 코사인 유사도: {similarity_b:.4f}")

# 더 유사한 컬럼 확인
if similarity_a > similarity_b:
    print("C는 A와 더 비슷합니다.")
elif similarity_b > similarity_a:
    print("C는 B와 더 비슷합니다.")
else:
    print("C와 A, B는 유사도가 같습니다.")


C와 A의 코사인 유사도: 0.4472
C와 B의 코사인 유사도: 0.8165
C는 B와 더 비슷합니다.


In [3]:
import pandas as pd

df = pd.read_csv('./input/train.csv')
#df = df [ df['SUBCLASS'].isin(['DLBC'] )]
df_test = pd.read_csv('./input/test.csv')


data = df.drop(columns=['ID', 'SUBCLASS'])
df_test.drop(columns=['ID'], inplace=True)
df_target = df['SUBCLASS']

In [68]:
raw_df_test = pd.read_csv('./input/test.csv') 

ID SUBCLASS    A2M AAAS AADAT AARS1 ABAT ABCA1 ABCA2 ABCA3  ...  \
0     TRAIN_0000    KIPAN     WT   WT    WT    WT   WT    WT    WT    WT  ...   
1     TRAIN_0001     SARC     WT   WT    WT    WT   WT    WT    WT    WT  ...   
2     TRAIN_0002     SKCM  R895R   WT    WT    WT   WT    WT    WT    WT  ...   
3     TRAIN_0003     KIRC     WT   WT    WT    WT   WT    WT    WT    WT  ...   
4     TRAIN_0004   GBMLGG     WT   WT    WT    WT   WT    WT    WT    WT  ...   
...          ...      ...    ...  ...   ...   ...  ...   ...   ...   ...  ...   
6196  TRAIN_6196     LUAD     WT   WT    WT    WT   WT    WT    WT    WT  ...   
6197  TRAIN_6197      LGG     WT   WT    WT    WT   WT    WT    WT    WT  ...   
6198  TRAIN_6198     COAD     WT   WT    WT    WT   WT    WT    WT    WT  ...   
6199  TRAIN_6199     TGCT     WT   WT    WT    WT   WT    WT    WT    WT  ...   
6200  TRAIN_6200     SKCM     WT   WT    WT    WT   WT    WT    WT    WT  ...   

     ZNF292 ZNF365 ZNF639 ZNF707 ZNFX1 ZNRF4 ZPBP ZW10  ZWINT ZYX  
0        WT     WT     WT     WT    WT    WT   WT   WT     WT  WT  
1        WT     WT     WT     WT    WT    WT   WT   WT     WT  WT  
2        WT     WT     WT     WT    WT    WT   WT   WT     WT  WT  
3        WT     WT     WT     WT    WT    WT   WT   WT     WT  WT  
4        WT     WT     WT     WT    WT    WT   WT   WT     WT  WT  
...     ...    ...    ...    ...   ...   ...  ...  ...    ...  ..  
6196     WT     WT     WT     WT    WT    WT   WT   WT     WT  WT  
6197     WT     WT     WT     WT    WT    WT   WT   WT     WT  WT  
6198     WT     WT     WT     WT    WT    WT   WT   WT  T181S  WT  
6199     WT     WT     WT     WT    WT    WT   WT   WT     WT  WT  
6200     WT     WT     WT     WT    WT    WT   WT   WT     WT  WT  

[6201 rows x 4386 columns]

In [ ]:
df_

In [5]:
total = pd.concat([data, df_test])
f = lambda x : 0 if x == 'WT' else 1
total = total.map(f)

In [6]:
data = total[:6201]

nRows = df.shape[0]
X = total[:nRows]
df_test = total[nRows:]

In [7]:
data

A2M  AAAS  AADAT  AARS1  ABAT  ABCA1  ABCA2  ABCA3  ABCA4  ABCA5  ...  \
0       0     0      0      0     0      0      0      0      0      0  ...   
1       0     0      0      0     0      0      0      0      0      0  ...   
2       1     0      0      0     0      0      0      0      0      0  ...   
3       0     0      0      0     0      0      0      0      0      0  ...   
4       0     0      0      0     0      0      0      0      0      0  ...   
...   ...   ...    ...    ...   ...    ...    ...    ...    ...    ...  ...   
6196    0     0      0      0     0      0      0      0      0      0  ...   
6197    0     0      0      0     0      0      0      0      0      0  ...   
6198    0     0      0      0     0      0      0      0      0      0  ...   
6199    0     0      0      0     0      0      0      0      0      0  ...   
6200    0     0      0      0     0      0      0      0      0      0  ...   

      ZNF292  ZNF365  ZNF639  ZNF707  ZNFX1  ZNRF4  ZPBP  ZW10  ZWINT  ZYX  
0          0       0       0       0      0      0     0     0      0    0  
1          0       0       0       0      0      0     0     0      0    0  
2          0       0       0       0      0      0     0     0      0    0  
3          0       0       0       0      0      0     0     0      0    0  
4          0       0       0       0      0      0     0     0      0    0  
...      ...     ...     ...     ...    ...    ...   ...   ...    ...  ...  
6196       0       0       0       0      0      0     0     0      0    0  
6197       0       0       0       0      0      0     0     0      0    0  
6198       0       0       0       0      0      0     0     0      1    0  
6199       0       0       0       0      0      0     0     0      0    0  
6200       0       0       0       0      0      0     0     0      0    0  

[6201 rows x 4384 columns]

In [8]:
df_test

A2M  AAAS  AADAT  AARS1  ABAT  ABCA1  ABCA2  ABCA3  ABCA4  ABCA5  ...  \
0       0     0      0      0     0      0      0      0      0      0  ...   
1       0     0      0      0     0      1      0      0      0      0  ...   
2       0     0      0      0     0      0      0      0      0      0  ...   
3       0     0      0      0     0      0      0      0      0      0  ...   
4       0     0      0      0     0      0      0      0      0      0  ...   
...   ...   ...    ...    ...   ...    ...    ...    ...    ...    ...  ...   
2541    0     0      0      0     0      0      0      0      0      0  ...   
2542    0     0      0      0     0      0      0      0      0      0  ...   
2543    0     0      0      0     0      1      1      1      1      1  ...   
2544    0     0      0      0     0      0      0      0      1      0  ...   
2545    0     0      0      0     0      0      0      0      0      0  ...   

      ZNF292  ZNF365  ZNF639  ZNF707  ZNFX1  ZNRF4  ZPBP  ZW10  ZWINT  ZYX  
0          0       0       0       0      0      0     0     0      0    0  
1          0       0       0       0      0      1     0     0      0    0  
2          0       0       0       0      0      0     0     0      0    0  
3          0       0       0       0      0      0     0     0      0    0  
4          0       0       0       0      0      0     0     0      0    0  
...      ...     ...     ...     ...    ...    ...   ...   ...    ...  ...  
2541       0       0       0       0      0      0     0     0      0    0  
2542       0       0       0       0      0      0     0     0      0    0  
2543       1       1       0       0      1      0     1     1      0    0  
2544       0       0       0       0      0      0     0     0      0    0  
2545       0       0       0       0      0      0     0     0      0    0  

[2546 rows x 4384 columns]

In [13]:
df_test.iloc[2543].values

array([0, 0, 0, ..., 1, 0, 0])

In [56]:
from sklearn.metrics.pairwise import cosine_similarity

# 두 데이터프레임의 코사인 유사도 계산
cosine_sim_matrix = cosine_similarity(df_test, data)

# cosine_sim_matrix[i, j]는 df_test의 i번째 행과 data의 j번째 행 간의 코사인 유사도


In [79]:
cosine_sim_matrix

array([[0.        , 0.03363364, 0.02542464, ..., 0.03466876, 0.        ,
        0.02001602],
       [0.02073903, 0.05029955, 0.06178718, ..., 0.02592379, 0.01959655,
        0.0823191 ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.07004379, 0.05460465, 0.12153854, ..., 0.03752346, 0.01891005,
        0.09387811],
       [0.        , 0.        , 0.040996  , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.14002801, 0.05292561, ..., 0.        , 0.        ,
        0.        ]])

In [58]:
cosine_sim_matrix.shape[0]

2546

In [61]:

# 데이터프레임의 'SUBCLASS' 컬럼을 가져오기
subclass_values = df['SUBCLASS'].values

# 각 행별로 가장 높은 2개의 유사도를 가진 'SUBCLASS' 값 찾기
top_subclasses = []

for i in range(cosine_sim_matrix.shape[0]):
    # 현재 행의 유사도 점수
    similarity_scores = cosine_sim_matrix[i]
    
    # 상위 2개 인덱스 찾기
    top_indices = np.argsort(similarity_scores)[-2:][::-1]  # 가장 높은 2개 인덱스
    
    # 해당 인덱스의 'SUBCLASS' 값 저장
    top_subclasses.append(subclass_values[top_indices])

# 결과 출력
top_subclasses_df = pd.DataFrame(top_subclasses, columns=['Top 1 SUBCLASS', 'Top 2 SUBCLASS'])


In [62]:
top_subclasses_df

Top 1 SUBCLASS Top 2 SUBCLASS
0              PCPG           BRCA
1              PAAD           UCEC
2              BRCA           THCA
3               LGG            LGG
4              LUAD            LGG
...             ...            ...
2541           THCA             OV
2542           PCPG             OV
2543           PAAD           UCEC
2544           LAML           LAML
2545         GBMLGG         GBMLGG

[2546 rows x 2 columns]

In [63]:
top_subclasses_df ['Top 1 SUBCLASS']

0         PCPG
1         PAAD
2         BRCA
3          LGG
4         LUAD
         ...  
2541      THCA
2542      PCPG
2543      PAAD
2544      LAML
2545    GBMLGG
Name: Top 1 SUBCLASS, Length: 2546, dtype: object

In [77]:
res001=pd.concat([raw_df_test.iloc[:,0],top_subclasses_df ['Top 1 SUBCLASS']],axis=1)
res001.to_csv('asdf01.csv',index=False)

In [78]:
res002=pd.concat([raw_df_test.iloc[:,0],top_subclasses_df ['Top 2 SUBCLASS']],axis=1)
res002.to_csv('asdf02.csv',index=False)

In [30]:
df.iloc[333]['SUBCLASS']

'LGG'

In [51]:
import numpy as np
threshold = 0.9
indices = np.argwhere((cosine_sim_matrix < threshold) & (cosine_sim_matrix > 0.5))


res = []
# 결과 출력
for i, j in indices:
    #print(f"Row {i} in df_test is similar to Row {j} {df.iloc[j]['SUBCLASS']} , in data with cosine similarity of {cosine_sim_matrix[i, j]}")
    res.append((i,j, df.iloc[j]['SUBCLASS']))
results_df = pd.DataFrame(res, columns=['test', 'data', 'class'])   
results_df

test  data   class
0        5  1202    UCEC
1        5  1369    SKCM
2        5  1761    UCEC
3        5  1789    PAAD
4        5  2189    UCEC
...    ...   ...     ...
1827  2545  5078     LGG
1828  2545  5267  GBMLGG
1829  2545  5545     LGG
1830  2545  5753     LGG
1831  2545  6130  GBMLGG

[1832 rows x 3 columns]

In [52]:
pivot=results_df.pivot_table(index='test', columns='class', aggfunc='size', fill_value=0)


In [53]:
pivot

class  BRCA  COAD  GBMLGG  HNSC  KIPAN  KIRC  LAML  LGG  OV  PAAD  PCPG  PRAD  \
test                                                                            
5         0     1       0     0      0     0     0    0   0     1     0     0   
7         0     1       0     0      0     0     0    0   0     1     0     0   
11        0     0       0     0      0     0     7    0   0     0     0     0   
22        0     0      19     0      0     0     3   18   0     0     0     0   
41        0     0       1     0      0     0     0    1   0     0     0     0   
...     ...   ...     ...   ...    ...   ...   ...  ...  ..   ...   ...   ...   
2468      0     1       0     0      0     0     0    0   0     1     0     0   
2483      0     0       0     0      0     0     0    1   0     0     0     0   
2543      0     0       0     0      0     0     0    0   0     1     0     0   
2544      0     0       0     0      0     0     1    0   0     0     0     0   
2545      0     0      18     0      0     0     3   17   0     0     0     0   

class  SARC  SKCM  STES  THCA  THYM  UCEC  
test                                       
5         0     1     0     0     0     6  
7         0     1     0     0     0     2  
11        0     0     0     0     0     0  
22        0     0     0     0     0     0  
41        0     0     0     0     0     0  
...     ...   ...   ...   ...   ...   ...  
2468      0     1     0     0     0     6  
2483      0     0     0    17     0     0  
2543      0     0     0     0     0     0  
2544      0     0     0     0     0     0  
2545      0     0     0     0     0     0  

[143 rows x 18 columns]

In [38]:
pivot.to_csv('pivot-line_similarity.csv')

In [47]:
filtered_pivot_table = pivot[(pivot <= 1).all(axis=1)]

In [48]:
filtered_pivot_table

class  BRCA  GBMLGG  HNSC  KIPAN  KIRC  LAML  LGG  PAAD  PCPG  PRAD  SKCM  \
test                                                                        
5         0       0     0      0     0     0    0     1     0     0     0   
22        0       1     0      0     0     0    0     0     0     0     0   
74        0       0     0      0     0     0    0     0     0     0     0   
145       0       0     0      0     0     0    0     0     0     0     0   
192       0       0     0      0     0     0    0     0     0     1     0   
352       0       0     0      1     1     0    0     0     1     0     0   
390       0       0     1      0     0     0    0     0     0     0     0   
519       0       0     0      0     0     0    0     0     0     0     0   
602       0       0     0      0     0     1    0     0     0     0     0   
637       0       0     0      0     0     0    0     0     0     0     0   
716       0       1     0      0     0     0    1     0     0     0     0   
886       0       1     0      0     0     0    1     0     0     0     0   
1009      0       0     0      0     0     0    0     0     0     0     1   
1078      1       0     0      0     0     0    0     0     0     1     0   
1162      0       0     0      0     0     0    0     1     0     0     0   
1213      1       0     0      0     0     0    0     0     0     0     0   
1222      0       0     0      0     0     0    0     1     0     0     1   
1264      1       0     0      0     0     0    0     0     0     0     0   
1560      1       0     0      0     0     0    0     0     0     1     0   
2096      0       1     0      0     0     0    1     0     0     0     0   
2447      0       0     0      0     0     0    0     0     0     0     0   
2545      0       1     0      0     0     0    0     0     0     0     0   

class  STES  THCA  THYM  UCEC  
test                           
5         0     0     0     0  
22        0     0     0     0  
74        0     1     0     0  
145       0     1     0     0  
192       0     0     0     0  
352       0     0     0     0  
390       0     0     0     0  
519       0     1     0     0  
602       0     0     0     0  
637       0     0     1     0  
716       0     0     0     0  
886       0     0     0     0  
1009      0     0     0     0  
1078      0     0     0     0  
1162      0     0     0     0  
1213      0     0     0     0  
1222      0     0     0     1  
1264      0     0     0     0  
1560      0     0     0     0  
2096      0     0     0     0  
2447      1     0     0     0  
2545      0     0     0     0

In [41]:
one_value_columns = []

# 각 행에 대해 반복
for index, row in filtered_pivot_table.iterrows():
    # 1인 열의 컬럼명 찾기
    columns_with_one = row[row == 1].index.tolist()  # 1인 컬럼명을 리스트로 변환
    one_value_columns.append((index, columns_with_one))  # (행 인덱스, 1인 컬럼명) 튜플 추가

# 결과 출력
for test_value, columns in one_value_columns:
    print(f"Test: {test_value}, Columns with value 1: {columns}")

Test: 3, Columns with value 1: ['LGG']
Test: 10, Columns with value 1: ['KIPAN']
Test: 14, Columns with value 1: ['KIPAN']
Test: 18, Columns with value 1: ['KIRC']
Test: 22, Columns with value 1: ['GBMLGG']
Test: 36, Columns with value 1: ['GBMLGG']
Test: 41, Columns with value 1: ['LGG']
Test: 46, Columns with value 1: ['KIPAN']
Test: 51, Columns with value 1: ['KIPAN']
Test: 91, Columns with value 1: ['KIPAN']
Test: 103, Columns with value 1: ['LGG']
Test: 104, Columns with value 1: ['GBMLGG']
Test: 116, Columns with value 1: ['KIRC']
Test: 127, Columns with value 1: ['LGG']
Test: 131, Columns with value 1: ['LAML']
Test: 154, Columns with value 1: ['KIPAN']
Test: 188, Columns with value 1: ['LGG']
Test: 200, Columns with value 1: ['KIPAN']
Test: 202, Columns with value 1: ['KIPAN']
Test: 212, Columns with value 1: ['LGG']
Test: 223, Columns with value 1: ['LGG']
Test: 247, Columns with value 1: ['LGG']
Test: 267, Columns with value 1: ['KIRC']
Test: 269, Columns with value 1: ['KIPA

In [27]:
indices

array([[   3,  333],
       [  10, 1702],
       [  14, 3970],
       ...,
       [2521, 5565],
       [2539, 3278],
       [2545, 1927]])

In [19]:
from sklearn.metrics.pairwise import cosine_similarity
for i in range(0, df_test.shape[0]):
    for j in range(0, data.shape[0]):
        a = df_test.iloc[i].values.reshape(1, -1)
        b = data.iloc[j].values.reshape(1, -1)
cosine_similarity(a,b)[0][0]

    

0.03363363969981562

In [36]:
import numpy as np
# 선택할 n개의 컬럼 (예: A, B, D)
n_columns = ['ABCA1', 'ABCA2' , 'ABCA3', 'ABCA4', 'ABCA5']
q = ['DDX10', 'ELOVL5']

# n개의 컬럼 값이 모두 1인 행을 찾음
rows_with_all_ones = data[data[q].eq(1).all(axis=1)]
print(rows_with_all_ones)


      A2M  AAAS  AADAT  AARS1  ABAT  ABCA1  ABCA2  ABCA3  ABCA4  ABCA5  ...  \
1202    1     0      0      0     0      0      0      0      1      1  ...   
4656    0     1      0      0     0      0      0      0      0      0  ...   
4984    0     1      0      0     0      0      1      1      1      1  ...   
5049    1     0      0      0     1      1      1      1      1      1  ...   

      ZNF292  ZNF365  ZNF639  ZNF707  ZNFX1  ZNRF4  ZPBP  ZW10  ZWINT  ZYX  
1202       1       0       1       0      1      0     1     0      0    1  
4656       1       0       0       0      1      0     0     0      0    0  
4984       1       1       1       0      1      0     0     0      0    1  
5049       1       1       0       1      1      0     0     1      0    0  

[4 rows x 4384 columns]


In [ ]:
rows_with_all_ones = data[data[q].eq(1).all(axis=1)]

In [41]:
data[(data == 1).all(axis=1)]

array([[1, 1, 1, 1, 1]])

In [42]:
data

array([[0, 1, 0, 1, 0],
       [1, 0, 1, 1, 0],
       [0, 1, 1, 0, 0],
       [1, 1, 0, 1, 1],
       [0, 0, 1, 0, 1],
       [1, 1, 1, 1, 0],
       [0, 1, 0, 0, 1],
       [1, 1, 1, 1, 1],
       [0, 0, 0, 1, 0],
       [1, 0, 1, 0, 1]])

In [2]:
import pandas as pd

# 예시 DataFrame 생성
data = {'A': [0, 1, 0, 1], 
        'B': [0, 0, 1, 0], 
        'C': [1, 1, 0, 0]}
df = pd.DataFrame(data)

# 1이 1개 이상 있는 행 필터링 (이 경우 1이 여러 개일 수도 있음)
one_2_rows = df[df.sum(axis=1) >= 1]

# 각 행에서 1이 위치한 열의 이름을 모두 나열하는 코드
result = [(index, row[row == 1].index.tolist()) for index, row in one_2_rows.iterrows()]

# 출력
print(result)


[(0, ['C']), (1, ['A', 'C']), (2, ['B']), (3, ['A'])]


In [3]:
qSet=['A','C']
# qSet에 해당하는 컬럼들만 값이 1인 행을 반환
df[(df[qSet].eq(1).all(axis=1)) & (df.drop(columns=qSet).eq(0).all(axis=1))]


A  B  C
1  1  0  1

In [46]:
import pandas as pd

# 예시 DataFrame
df = pd.DataFrame({
    'a': [0, 0, 1, 0],
    'b': [0, 0, 0, 0],
    'q': [1, 0, 1, 1]
})

# 'q' 컬럼이 1이고 다른 모든 컬럼이 0인 행만 선택
filtered_df = df[(df['q'] == 1) & (df.drop(columns='q') == 0).all(axis=1)]

print(filtered_df)


   a  b  q
0  0  0  1
3  0  0  1


In [ ]:

# DataFrame A에서 1, 2번째 열만 선택
A_selected = df_test.iloc[:, [0, 1]]  # 0, 1 인덱스는 첫 번째와 두 번째 열

# DataFrame A_selected와 B 합성 (열 기준 합성)
result = pd.concat([A_selected, rdf], axis=1)
result